netG:
  _target_: ttslearn.wavenet.WaveNet
  out_channels: 256
  layers: 30
  stacks: 3
  residual_channels: 64
  gate_channels: 128
  skip_out_channels: 64
  kernel_size: 3
  cin_channels: 80
  upsample_scales: [2, 4, 5, 5] # np.prod(upsample_scales) = 200
  aux_context_window: 2
